In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\user\Documents\machine-learning\Data\iris.csv')

### Numpy Fundamentals and Essentials

In [3]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [4]:
# values berfungsi untuk mengubah dari dataframe ke numeric
iris_data_numeric = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)']].values

Numpy Array

In [5]:
list_p = [1,2,3,4,5]
array_from_list = np.array(list_p)

In [6]:
print(f"this is list: {list_p}")
# this is deffirent beetwent array and list
print(f"this is array: {array_from_list}")

this is list: [1, 2, 3, 4, 5]
this is array: [1 2 3 4 5]


In [7]:
list_p[1]

2

In [8]:
array_from_list[1]

np.int64(2)

In [9]:
# np.zeros()
# np.zeros((x, y)) 
np.zeros(shape=(3, 3))# 2 dimensi

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((3, 3, 3))# 3 dimensi
# tergantung jumlah value yang diinput 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# np.ones((x, y))
# konsepnya than np.zeros(())
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
# np.arange(start, stop, step) is similiar with for loop and method range()
np.arange(1, 13, 2)

array([ 1,  3,  5,  7,  9, 11])

## Random value numpy array
np.random.rand() -> random float

np.random.randiant() -> random int

In [13]:
# np.random.rand() -> hanya menampilkan float beetwen 0 and 1.
random_float_numpy = np.random.rand(5, 5)
random_float_numpy

array([[0.76703873, 0.09221906, 0.80237833, 0.4880303 , 0.62845652],
       [0.16872796, 0.04048203, 0.49121125, 0.21858918, 0.75663368],
       [0.6638941 , 0.80750342, 0.5908554 , 0.21054635, 0.36826548],
       [0.64513179, 0.23741559, 0.82729407, 0.45693355, 0.94841282],
       [0.55734094, 0.28091233, 0.43053269, 0.53729125, 0.13938778]])

In [14]:
np.random.randint(1, 20, size=(3, 3, 3))# size itu berfungsi untuk memanipulasi dimensi


array([[[14, 15, 19],
        [ 4, 11, 19],
        [ 8,  1, 15]],

       [[ 5,  4,  5],
        [15,  9, 15],
        [ 3, 18, 19]],

       [[ 9, 15,  8],
        [14, 12, 13],
        [10,  1, 10]]], dtype=int32)

## Reshaping array

In [15]:
old_array = np.arange(1, 11)
old_array # old_array = 1 x 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# jadi nilai array yang dibuat harus memiliki hasil 10
reshap_old_array = old_array.reshape(2, 5)
reshap_old_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Indexing and Slicing

In [17]:
# mengakses data used method slicing
# iris_data_numeric[start:stop:step, start:stop:step]
# [row, colom] -> [start:stop:step, start:stop:step]
single_elem = iris_data_numeric[0:0]
single_elem

array([], shape=(0, 3), dtype=float64)

In [18]:
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [19]:
iris_data_numeric[0:2, 0:3]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4]])

In [20]:
iris_data_numeric[:, -2:]# : untuk akses semuanya

array([[3.5, 1.4],
       [3. , 1.4],
       [3.2, 1.3],
       [3.1, 1.5],
       [3.6, 1.4],
       [3.9, 1.7],
       [3.4, 1.4],
       [3.4, 1.5],
       [2.9, 1.4],
       [3.1, 1.5],
       [3.7, 1.5],
       [3.4, 1.6],
       [3. , 1.4],
       [3. , 1.1],
       [4. , 1.2],
       [4.4, 1.5],
       [3.9, 1.3],
       [3.5, 1.4],
       [3.8, 1.7],
       [3.8, 1.5],
       [3.4, 1.7],
       [3.7, 1.5],
       [3.6, 1. ],
       [3.3, 1.7],
       [3.4, 1.9],
       [3. , 1.6],
       [3.4, 1.6],
       [3.5, 1.5],
       [3.4, 1.4],
       [3.2, 1.6],
       [3.1, 1.6],
       [3.4, 1.5],
       [4.1, 1.5],
       [4.2, 1.4],
       [3.1, 1.5],
       [3.2, 1.2],
       [3.5, 1.3],
       [3.6, 1.4],
       [3. , 1.3],
       [3.4, 1.5],
       [3.5, 1.3],
       [2.3, 1.3],
       [3.2, 1.3],
       [3.5, 1.6],
       [3.8, 1.9],
       [3. , 1.4],
       [3.8, 1.6],
       [3.2, 1.4],
       [3.7, 1.5],
       [3.3, 1.4],
       [3.2, 4.7],
       [3.2, 4.5],
       [3.1,

In [21]:
sepal_length = iris_data_numeric[iris_data_numeric[:, 0] > 5.0]
sepal_length

array([[5.1, 3.5, 1.4],
       [5.4, 3.9, 1.7],
       [5.4, 3.7, 1.5],
       [5.8, 4. , 1.2],
       [5.7, 4.4, 1.5],
       [5.4, 3.9, 1.3],
       [5.1, 3.5, 1.4],
       [5.7, 3.8, 1.7],
       [5.1, 3.8, 1.5],
       [5.4, 3.4, 1.7],
       [5.1, 3.7, 1.5],
       [5.1, 3.3, 1.7],
       [5.2, 3.5, 1.5],
       [5.2, 3.4, 1.4],
       [5.4, 3.4, 1.5],
       [5.2, 4.1, 1.5],
       [5.5, 4.2, 1.4],
       [5.5, 3.5, 1.3],
       [5.1, 3.4, 1.5],
       [5.1, 3.8, 1.9],
       [5.1, 3.8, 1.6],
       [5.3, 3.7, 1.5],
       [7. , 3.2, 4.7],
       [6.4, 3.2, 4.5],
       [6.9, 3.1, 4.9],
       [5.5, 2.3, 4. ],
       [6.5, 2.8, 4.6],
       [5.7, 2.8, 4.5],
       [6.3, 3.3, 4.7],
       [6.6, 2.9, 4.6],
       [5.2, 2.7, 3.9],
       [5.9, 3. , 4.2],
       [6. , 2.2, 4. ],
       [6.1, 2.9, 4.7],
       [5.6, 2.9, 3.6],
       [6.7, 3.1, 4.4],
       [5.6, 3. , 4.5],
       [5.8, 2.7, 4.1],
       [6.2, 2.2, 4.5],
       [5.6, 2.5, 3.9],
       [5.9, 3.2, 4.8],
       [6.1, 2.8

### operasi numpy(aritmatika & aggregation)

In [22]:
# persyaratan operasi adalah panjang data harus sama 
# dan data15 = np.arange(1, b)
# data510 = np.arange(c, 11). b dan c angkanya harus sama
data15 = np.arange(1, 6)
data510 = np.arange(6, 11)

In [23]:
data15.shape
data510.shape

(5,)

In [24]:
data_sum = data15 + data510
data_sum

array([ 7,  9, 11, 13, 15])

In [25]:
data_substrac = data510 - data15
data_substrac

array([5, 5, 5, 5, 5])

## Numpy part 2: numpy operation & broadcasting


In [26]:
# np.sqrt() -> menghitung akar kuadrat disetiap elemen didalam array
data = np.random.randint(10, 100, size=(3, 3))
data

array([[77, 99, 69],
       [86, 96, 86],
       [11, 89, 56]], dtype=int32)

In [27]:
data_sqrt = np.sqrt(data)
data_sqrt

array([[8.77496439, 9.94987437, 8.30662386],
       [9.2736185 , 9.79795897, 9.2736185 ],
       [3.31662479, 9.43398113, 7.48331477]])

In [28]:
# np.log() -> mencari logaritma(pangkat berap yang harus diberikan agar suatu bilangan bisa menghasilkan bilangan tertentu)
data_log = np.log(data)
data_log

array([[4.34380542, 4.59511985, 4.2341065 ],
       [4.4543473 , 4.56434819, 4.4543473 ],
       [2.39789527, 4.48863637, 4.02535169]])

In [29]:
data_log2 = np.log2(data)
data_log2

array([[6.26678654, 6.62935662, 6.10852446],
       [6.42626475, 6.5849625 , 6.42626475],
       [3.45943162, 6.47573343, 5.80735492]])

In [30]:
# np.exp() np.sin() np.cos()

In [31]:
sin_array = np.array([[0, 30, 45, 60, 90, 120, 135, 150, 180]])
print(f"ini sin-nya:{np.sin(sin_array)}")

ini sin-nya:[[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118
   0.08836869 -0.71487643 -0.80115264]]


In [32]:
print(f"ini cos: {np.cos(sin_array)}")

ini cos: [[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097
  -0.99608784  0.69925081 -0.59846007]]


In [33]:
print(f"ini exp: {np.exp(sin_array)}")

ini exp: [[1.00000000e+00 1.06864746e+13 3.49342711e+19 1.14200739e+26
  1.22040329e+39 1.30418088e+52 4.26338995e+58 1.39370958e+65
  1.48938420e+78]]


In [34]:
m1 = np.array([[2,3,1],
               [7,6,1]])
m2 = np.array([[1, 2],
               [5,3],
               [1,1]])
np.matmul(m1, m2)

array([[18, 14],
       [38, 33]])

In [35]:
# method untuk mencari matriks multiplication
a = np.array([[-5, 3],
              [-2, 1]])
b = np.array([[-3, -1],
              [1, 1]])



### 2 method dari numpy ini berfungsi untuk mencari matriks multiplication dan dot product


In [36]:
np.matmul(a, b)

array([[18,  8],
       [ 7,  3]])

In [37]:
np.dot(a, b)

array([[18,  8],
       [ 7,  3]])

In [38]:
# method untuk mencari dot product
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])


In [39]:
print(np.matmul(v1, v2))


32


In [40]:
print(np.dot(v1, v2))

32


### Broadcasting

In [41]:
# ini yang dinamakan broadcasting
# jadi broadcasting itu berfungsi untuk mengoperasikan semuanya dengan vektor/ matriks yang berbeda dimensi
v = np.array([1,2,3])
s = 10
hasil = v + s


In [42]:
hasil

array([11, 12, 13])

In [43]:
c = np.array([[1, 3, 4],
              [4, 6, 7]])
l = np.array([10, 20, 30])
# broadcasting terjadi jika 
# this is a rule broadcasting
# lev(l) == 1
# len(l) == colom(colom c)
# len(l) == row/baris(row c)
hasil = c + l

In [44]:
hasil

array([[11, 23, 34],
       [14, 26, 37]])

In [45]:
# matriks with vektor
m = np.array([[1, 2, 3], 
             [4, 5, 6]]) 
v= np.array([[100],
     [200]])
hasi2l = m + v


In [46]:
hasi2l

array([[101, 102, 103],
       [204, 205, 206]])

In [47]:
o = np.array([[4, 5, 1],
              [6, 8, 6]])
p = np.array([[10],
              [20]])
result = o + p

In [48]:
result

array([[14, 15, 11],
       [26, 28, 26]])

In [49]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [50]:
iris_data_numeric[1:,1:] 

array([[3. , 1.4],
       [3.2, 1.3],
       [3.1, 1.5],
       [3.6, 1.4],
       [3.9, 1.7],
       [3.4, 1.4],
       [3.4, 1.5],
       [2.9, 1.4],
       [3.1, 1.5],
       [3.7, 1.5],
       [3.4, 1.6],
       [3. , 1.4],
       [3. , 1.1],
       [4. , 1.2],
       [4.4, 1.5],
       [3.9, 1.3],
       [3.5, 1.4],
       [3.8, 1.7],
       [3.8, 1.5],
       [3.4, 1.7],
       [3.7, 1.5],
       [3.6, 1. ],
       [3.3, 1.7],
       [3.4, 1.9],
       [3. , 1.6],
       [3.4, 1.6],
       [3.5, 1.5],
       [3.4, 1.4],
       [3.2, 1.6],
       [3.1, 1.6],
       [3.4, 1.5],
       [4.1, 1.5],
       [4.2, 1.4],
       [3.1, 1.5],
       [3.2, 1.2],
       [3.5, 1.3],
       [3.6, 1.4],
       [3. , 1.3],
       [3.4, 1.5],
       [3.5, 1.3],
       [2.3, 1.3],
       [3.2, 1.3],
       [3.5, 1.6],
       [3.8, 1.9],
       [3. , 1.4],
       [3.8, 1.6],
       [3.2, 1.4],
       [3.7, 1.5],
       [3.3, 1.4],
       [3.2, 4.7],
       [3.2, 4.5],
       [3.1, 4.9],
       [2.3,

In [51]:
# np.concatenate

data_array_1 = np.array([[2, 3], [4, 5], [3, 9]])
data_array_2 = np.array([[10, 11], [19, 20], [35, 32]])

In [52]:
np.concatenate((data_array_1, data_array_2), axis=1) # menjadi colom    
# axis 0 = baris/row
# axis 1 = colom 


array([[ 2,  3, 10, 11],
       [ 4,  5, 19, 20],
       [ 3,  9, 35, 32]])

In [53]:
np.concatenate((data_array_1, data_array_2), axis=0) # menjadi baris

array([[ 2,  3],
       [ 4,  5],
       [ 3,  9],
       [10, 11],
       [19, 20],
       [35, 32]])

In [54]:
array_v2 = np.array([[30, 20], 
                     [40, 50]])
array_v1 = np.array([[90],
                     [100]])

np.concatenate((array_v1, array_v2), axis=1)

array([[ 90,  30,  20],
       [100,  40,  50]])

In [55]:
# np.concatenate((array_v1, array_v2), axis=0)
# output error because colom and row itu tidak sama jika axis = 0